services:
  - type: web
    name: adtv-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://adtv-backend.onrender.com
      - key: VITE_ADTV_API_URL
        value: https://adtv-events-server.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: adtv-backend
    env: python
    region: oregon
    plan: standard
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false

  - type: web
    name: adtv-events-server
    env: node
    region: oregon
    plan: starter
    rootDir: adtv-migration-package/apps/server
    buildCommand: corepack enable && pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://alliance_2025_db_user:dob8oPy5OmzPuTkrDS6yjgrcbm1LBUAH@dpg-d1cq41jipnbc73c2vdag-a/alliance_2025_db
      - key: JWT_SECRET
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://adtv-events-server.onrender.com
      - key: PORT
        value: 4000
      - key: SMS_PROVIDER
        value: twilio
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false